"""Stable typed risk reason codes."""

from __future__ import annotations

from enum import Enum


class RiskReason(str, Enum):
    APPROVED = "APPROVED"
    MODE_NOT_EXECUTABLE = "MODE_NOT_EXECUTABLE"
    LIVE_NOT_SUPPORTED = "LIVE_NOT_SUPPORTED"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    DUPLICATE_INTENT = "DUPLICATE_INTENT"
    UNKNOWN_INSTRUMENT = "UNKNOWN_INSTRUMENT"
    MARKET_MISMATCH = "MARKET_MISMATCH"
    MARKET_NOT_ACTIVE = "MARKET_NOT_ACTIVE"
    ENTRY_WINDOW_CLOSED = "ENTRY_WINDOW_CLOSED"
    DATA_UNINITIALIZED = "DATA_UNINITIALIZED"
    DATA_STALE = "DATA_STALE"
    FUTURE_TIMESTAMP = "FUTURE_TIMESTAMP"
    BOOK_RECOVERY_REQUIRED = "BOOK_RECOVERY_REQUIRED"
    PRICE_OUT_OF_BOUNDS = "PRICE_OUT_OF_BOUNDS"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    INSUFFICIENT_LIQUIDITY = "INSUFFICIENT_LIQUIDITY"
    INVALID_NOTIONAL = "INVALID_NOTIONAL"
    NOTIONAL_LIMIT_EXCEEDED = "NOTIONAL_LIMIT_EXCEEDED"
    UNSUPPORTED_INTENT = "UNSUPPORTED_INTENT"
    RESOLUTION_CAPABILITY_UNAVAILABLE = "RESOLUTION_CAPABILITY_UNAVAILABLE"
    INTERNAL_POLICY_ERROR = "INTERNAL_POLICY_ERROR"
    BOOK_ONE_SIDED_OR_EMPTY = "BOOK_ONE_SIDED_OR_EMPTY"
    PORTFOLIO_UNAVAILABLE = "PORTFOLIO_UNAVAILABLE"
    POSITION_LIMIT_EXCEEDED = "POSITION_LIMIT_EXCEEDED"
    PENDING_ORDER_BLOCKS_ENTRY = "PENDING_ORDER_BLOCKS_ENTRY"
    ACTIVE_POSITION_BLOCKS_ENTRY = "ACTIVE_POSITION_BLOCKS_ENTRY"
    EXIT_EXCEEDS_POSITION = "EXIT_EXCEEDS_POSITION"
    EXIT_INCREASES_EXPOSURE = "EXIT_INCREASES_EXPOSURE"
