"""Stable N7 abort / skip reason codes."""

from __future__ import annotations

from enum import Enum


class N7AbortCode(str, Enum):
    AUTHORIZATION_ABSENT = "authorization_absent"
    AUTHORIZATION_MISMATCH = "authorization_mismatch"
    AUTHORIZATION_EXPIRED = "authorization_expired"
    AUTHORIZATION_CONSUMED = "authorization_consumed"
    DIRTY_WORKTREE = "dirty_worktree"
    CONFIGURATION_MISMATCH = "configuration_mismatch"
    HEAD_MISMATCH = "head_mismatch"
    CONNECTIVITY_UNAVAILABLE = "connectivity_unavailable"
    CREDENTIALS_ROLE_MISMATCH = "credentials_role_mismatch"
    PREFLIGHT_RECON_DISAGREEMENT = "preflight_reconciliation_disagreement"
    UNEXPECTED_OPEN_ORDER = "unexpected_open_order"
    SELECTED_MARKET_EXPOSURE_PRESENT = "selected_market_exposure_present"
    CLOCK_NOT_READY = "clock_not_ready"
    PTB_ABSENT = "ptb_absent"
    PTB_NOT_ATTESTED = "ptb_not_attested"
    PTB_NOT_LOCKED = "ptb_not_locked"
    CRITICAL_FEED_STALE = "critical_feed_stale"
    LATE_ENTRY = "late_entry"
    VENUE_MINIMUM_ABOVE_CAP = "venue_minimum_above_cap"
    RISK_OR_DAILY_LIMIT_BREACH = "risk_or_daily_limit_breach"
    KILL_ACTIVE = "kill_active"
    AMBIGUOUS_ACKNOWLEDGMENT = "ambiguous_acknowledgment"
    UNKNOWN_INVENTORY = "unknown_inventory"
    EXIT_RETRY_BUDGET_EXHAUSTED = "exit_retry_budget_exhausted"
    RESIDUAL_EXPOSURE_AT_DEADLINE = "residual_exposure_at_deadline"
    TERMINAL_FLAT = "terminal_flat"
    INTENTIONAL_NO_SIGNAL_SKIP = "intentional_no_signal_skip"
    SCOPE_B_REFUSED = "scope_b_refused"
    HOLD_TO_RESOLUTION_REFUSED = "hold_to_resolution_refused"
    REDEEM_REFUSED = "redeem_refused"
    SECOND_WINDOW_REFUSED = "second_window_refused"
    REENTRY_REFUSED = "reentry_refused"
    REVERSAL_REFUSED = "reversal_refused"
    CANCEL_ALL_REFUSED = "cancel_all_refused"
    ALLOWANCE_MUTATION_REFUSED = "allowance_mutation_refused"
    TRANSFER_REFUSED = "transfer_refused"
    HISTORICAL_AS_STRATEGY_REFUSED = "historical_as_strategy_refused"
    CTRL_C_ABORT = "ctrl_c_abort"
    CRASH_MUTATIONS_DISABLED = "crash_mutations_disabled"
    BINDING_ALREADY_SET = "binding_already_set"
    MARKET_OUTSIDE_ENVELOPE = "market_outside_envelope"
