"""Stable Z-Gap reason codes for pure policy/valuation results."""

from __future__ import annotations

from enum import Enum


class ZGapReason(str, Enum):
    # Readiness / quality
    MODEL_READY = "MODEL_READY"
    MODEL_NOT_READY = "MODEL_NOT_READY"
    PTB_NOT_USABLE = "PTB_NOT_USABLE"
    TIME_NOT_READY = "TIME_NOT_READY"
    BASIS_REJECT = "BASIS_REJECT"
    SIGMA_NOT_READY = "SIGMA_NOT_READY"
    JUMP_GUARD = "JUMP_GUARD"
    TAU_OUT_OF_BAND = "TAU_OUT_OF_BAND"
    Z_OUT_OF_BAND = "Z_OUT_OF_BAND"
    ABS_Z_BLOCK = "ABS_Z_BLOCK"
    BOOK_NOT_READY = "BOOK_NOT_READY"
    BOOK_UNAVAILABLE = "BOOK_UNAVAILABLE"
    BOOK_SYNCING = "BOOK_SYNCING"
    BOOK_STALE = "BOOK_STALE"
    BOOK_DESYNCED = "BOOK_DESYNCED"
    VENUE_BID_EXPLICITLY_EMPTY = "VENUE_BID_EXPLICITLY_EMPTY"
    VENUE_ASK_EXPLICITLY_EMPTY = "VENUE_ASK_EXPLICITLY_EMPTY"
    INSUFFICIENT_DEPTH = "INSUFFICIENT_DEPTH"
    FEE_NOT_READY = "FEE_NOT_READY"
    FEE_UNAVAILABLE = "FEE_UNAVAILABLE"
    EPOCH_MISMATCH = "EPOCH_MISMATCH"
    WINDOW_MISMATCH = "WINDOW_MISMATCH"
    STALE_COMPONENT = "STALE_COMPONENT"

    # Entry / selection
    NO_ECONOMIC_EDGE = "NO_ECONOMIC_EDGE"
    BELOW_THRESHOLD = "BELOW_THRESHOLD"
    TIE_AMBIGUOUS = "TIE_AMBIGUOUS"
    BOTH_LEGS_EDGE = "BOTH_LEGS_EDGE"
    ENTRY_CANDIDATE = "ENTRY_CANDIDATE"
    LEG_NOT_READY = "LEG_NOT_READY"
    WAIT = "WAIT"
    SKIP = "SKIP"

    # Thesis
    THESIS_VALID = "THESIS_VALID"
    THESIS_CONFIRMING = "THESIS_CONFIRMING"
    THESIS_INVALID = "THESIS_INVALID"
    THESIS_RESET_STALE = "THESIS_RESET_STALE"

    # Realization / time
    MARKET_RICH_EXIT = "MARKET_RICH_EXIT"
    TIME_SELL = "TIME_SELL"
    RESOLUTION_PREFERENCE = "RESOLUTION_PREFERENCE"
    CONTINUE_HOLD = "CONTINUE_HOLD"
    SELL_BEATS_RESOLUTION = "SELL_BEATS_RESOLUTION"

    # Precedence / block
    UNKNOWN_STATE = "UNKNOWN_STATE"
    EMERGENCY_FLAG = "EMERGENCY_FLAG"
    BLOCKED = "BLOCKED"
